
# The mnemonic that you used to generate your
# keys.
#
# It is recommended not to use this
# argument, and wait for the CLI to ask you
#    for your mnemonic as otherwise it will
#    appear in your shell history.
mnemonic = "palace parade smoke alert thought ship luggage crouch during shrug budget height fan author ask wear catch gaze half girl song tunnel fossil wasp"

# The name of Ethereum PoS chain you are targeting [possible values: Mainnet, Holesky, Prater, Goerli]
chain = "Holesky"

# The number of new validator keys you want to generate [aliases: num_validators]
num_validators = 1

# The password that will secure your keystores [aliases: keystore_password]
keystore_password = "11111111"

# The index of the first validator's keys you wish to generate the address for [aliases: validator_start_index]
validator_start_index = 0

# If this field is set and valid,
# the given value will be used to set the withdrawal credentials.
# Otherwise, it will generate withdrawal credentials with the mnemonic-derived withdrawal public key.
# Valid formats are
# ^(0x[a-fA-F0-9]{40})$ for execution addresses,
# ^(0x01[0]{22}[a-fA-F0-9]{40})$ for execution withdrawal credentials and
# ^(0x00[a-fA-F0-9]{62})$ for BLS withdrawal credentials [aliases: withdrawal_credentials]
withdrawal_credentials = "0x28B9FEAE1f3d76565AAdec86E7401E815377D9Cc"

# Use this argument to select the key derivation function for the keystores [possible values: Scrypt, Pbkdf2]
kdf = ""

# Path to a custom Eth PoS chain config
testnet_config = ""

# A version of CLI to include into generated deposit data
deposit_cli_version = "2.7.0"

staking_rpc = "https://ethereum-holesky-rpc.publicnode.com"

from_path = "./sk"

staking_address = ""